import { Project, Skill, ContactFormData, SkillCategory, Book, Certification } from '@/types';
import { getAssetPath } from './utils';

// Mock Projects
export const projects: Project[] = [
  {
    _id: '4',
    title: 'Pharmacy Management System',
    description: 'A console-based system using Java and PostgreSQL for managing drug inventory and transactions. This application helps pharmacies track inventory, manage prescriptions, and process sales.\n\nThe system includes features for user authentication, inventory management, sales tracking, and reporting.',
    image: getAssetPath('/images/projects/pharmacy-system.jpg'),
    technologies: ['Java', 'PostgreSQL', 'JDBC', 'Console App'],
    githubUrl: 'https://github.com/AnkushGitRepo/Pharmacy-Management-System',
    liveUrl: '',
    featured: true,
    category: 'Desktop Application',
    createdAt: new Date().toISOString(),
  },
];

// Mock Skills
export const skills: Skill[] = [
  // Languages
  {
    _id: '1',
    name: 'Java',
    category: SkillCategory.LANGUAGES,
    icon: '/images/skills/icons8-java.svg',
  },
  {
    _id: '2',
    name: 'Python',
    category: SkillCategory.LANGUAGES,
    icon: '/images/skills/icons8-python.svg',
  },
  {
    _id: '3',
    name: 'JavaScript',
    category: SkillCategory.LANGUAGES,
    icon: '/images/skills/icons8-javascript.svg',
  },
  {
    _id: '4',
    name: 'HTML',
    category: SkillCategory.LANGUAGES,
    icon: '/images/skills/icons8-html5.svg',
  },
  {
    _id: '5',
    name: 'CSS',
    category: SkillCategory.LANGUAGES,
    icon: '/images/skills/icons8-css.svg',
  },
  {
    _id: '6',
    name: 'TypeScript',
    category: SkillCategory.LANGUAGES,
    icon: '/images/skills/icons8-typescript.svg',
  },

  // Frameworks & Libraries
  {
    _id: '7',
    name: 'React',
    category: SkillCategory.FRAMEWORKS,
    icon: '/images/skills/icons8-react.svg',
  },
  {
    _id: '8',
    name: 'Node.js',
    category: SkillCategory.FRAMEWORKS,
    icon: '/images/skills/icons8-nodejs.svg',
  },
  {
    _id: '9',
    name: 'Express.js',
    category: SkillCategory.FRAMEWORKS,
    icon: '/images/skills/icons8-express-js.svg',
  },
  {
    _id: '10',
    name: 'Bootstrap',
    category: SkillCategory.FRAMEWORKS,
    icon: '/images/skills/icons8-bootstrap.svg',
  },
  {
    _id: '11',
    name: 'Tailwind CSS',
    category: SkillCategory.FRAMEWORKS,
    icon: '/images/skills/icons8-tailwind-css.svg',
  },

  // Databases
  {
    _id: '12',
    name: 'MySQL',
    category: SkillCategory.DATABASES,
    icon: '/images/skills/icons8-mysql.svg',
  },
  {
    _id: '13',
    name: 'PostgreSQL',
    category: SkillCategory.DATABASES,
    icon: '/images/skills/icons8-postgres.svg',
  },
  {
    _id: '14',
    name: 'MongoDB',
    category: SkillCategory.DATABASES,
    icon: '/images/skills/MongoDB.svg',
  },
  {
    _id: '15',
    name: 'Redis',
    category: SkillCategory.DATABASES,
    icon: '/images/skills/icons8-redis.svg',
  },

  // Tools & IDEs
  {
    _id: '16',
    name: 'Git',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-git.svg',
  },
  {
    _id: '17',
    name: 'GitHub',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-github.svg',
  },
  {
    _id: '18',
    name: 'VS Code',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-visual-studio.svg',
  },
  {
    _id: '19',
    name: 'IntelliJ IDEA',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-intellij-idea.svg',
  },
  {
    _id: '20',
    name: 'PyCharm',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-pycharm.svg',
  },
  {
    _id: '21',
    name: 'WebStorm',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-webstorm.svg',
  },
  {
    _id: '22',
    name: 'Jupyter',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-jupyter.svg',
  },
  {
    _id: '23',
    name: 'Figma',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-figma.svg',
  },
];

// Mock Books
export const books: Book[] = [
  {
    _id: '1',
    title: 'Atomic Habits',
    author: 'James Clear',
    image: getAssetPath('/placeholder.svg'),
    coverImage: getAssetPath('/placeholder.svg'),
    description: 'An easy and proven way to build good habits and break bad ones.',
    review: 'This book changed my perspective on how habits form and how small changes can lead to remarkable results. The 1% improvement philosophy is something I apply daily.',
    rating: 5,
    genre: ['Self-Help', 'Psychology', 'Productivity'],
    publishedYear: 2018,
    readDate: '2022-06-15',
    amazonLink: 'https://www.amazon.com/Atomic-Habits-Proven-Build-Break/dp/0735211299',
    goodreadsLink: 'https://www.goodreads.com/book/show/40121378-atomic-habits',
    order: 1,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '2',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    image: getAssetPath('/placeholder.svg'),
    coverImage: getAssetPath('/placeholder.svg'),
    description: 'A groundbreaking narrative of humanity\'s creation and evolution that explores how biology and history have defined us.',
    review: 'Harari\'s ability to connect historical dots and present a cohesive narrative of human history is remarkable. This book made me question many assumptions about society and human progress.',
    rating: 5,
    genre: ['History', 'Anthropology', 'Science'],
    publishedYear: 2011,
    readDate: '2021-08-20',
    amazonLink: 'https://www.amazon.com/Sapiens-Humankind-Yuval-Noah-Harari/dp/0062316095',
    goodreadsLink: 'https://www.goodreads.com/book/show/23692271-sapiens',
    order: 2,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '3',
    title: 'Deep Work',
    author: 'Cal Newport',
    image: getAssetPath('/placeholder.svg'),
    coverImage: getAssetPath('/placeholder.svg'),
    description: 'Rules for focused success in a distracted world.',
    review: 'In an age of constant distraction, Newport\'s concept of deep work has been transformative for my productivity. The practical strategies for achieving focused work have helped me accomplish more meaningful tasks.',
    rating: 4,
    genre: ['Productivity', 'Business', 'Self-Help'],
    publishedYear: 2016,
    readDate: '2022-01-10',
    amazonLink: 'https://www.amazon.com/Deep-Work-Focused-Success-Distracted/dp/1455586692',
    goodreadsLink: 'https://www.goodreads.com/book/show/25744928-deep-work',
    order: 3,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '4',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    image: getAssetPath('/placeholder.svg'),
    coverImage: getAssetPath('/placeholder.svg'),
    description: 'Timeless lessons on wealth, greed, and happiness.',
    review: 'Housel presents financial concepts through compelling stories that highlight how psychology affects our financial decisions. The book changed how I think about money, success, and happiness.',
    rating: 5,
    genre: ['Finance', 'Psychology', 'Economics'],
    publishedYear: 2020,
    readDate: '2022-11-05',
    amazonLink: 'https://www.amazon.com/Psychology-Money-Timeless-lessons-happiness/dp/0857197681',
    goodreadsLink: 'https://www.goodreads.com/book/show/41881472-the-psychology-of-money',
    order: 4,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '5',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    image: getAssetPath('/placeholder.svg'),
    coverImage: getAssetPath('/placeholder.svg'),
    description: 'A groundbreaking tour of the mind explaining the two systems that drive the way we think.',
    review: 'Kahneman\'s exploration of cognitive biases and the two systems of thinking provides profound insights into human decision-making. This book has made me more aware of my own thinking patterns and biases.',
    rating: 5,
    genre: ['Psychology', 'Economics', 'Science'],
    publishedYear: 2011,
    readDate: '2021-03-15',
    amazonLink: 'https://www.amazon.com/Thinking-Fast-Slow-Daniel-Kahneman/dp/0374533555',
    goodreadsLink: 'https://www.goodreads.com/book/show/11468377-thinking-fast-and-slow',
    order: 5,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '6',
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    image: getAssetPath('/placeholder.svg'),
    coverImage: getAssetPath('/placeholder.svg'),
    description: 'From the Big Bang to Black Holes.',
    review: 'Hawking\'s ability to explain complex cosmological concepts in accessible language is remarkable. This book sparked my interest in physics and the universe\'s mysteries.',
    rating: 4,
    genre: ['Science', 'Physics', 'Cosmology'],
    publishedYear: 1988,
    readDate: '2020-07-22',
    amazonLink: 'https://www.amazon.com/Brief-History-Time-Stephen-Hawking/dp/0553380168',
    goodreadsLink: 'https://www.goodreads.com/book/show/3869.A_Brief_History_of_Time',
    order: 6,
    createdAt: new Date().toISOString(),
  },
];

// Mock Certifications
export const certifications: Certification[] = [
  {
    _id: '1',
    title: 'Python 3 Programming',
    issuer: 'Coursera & University of Michigan',
    description: 'This specialization teaches the fundamentals of Python 3 programming. It covers Python basics, data structures, file handling, and advanced concepts like object-oriented programming. The specialization includes hands-on projects to build practical programming skills.',
    image: '/images/certificates/Python_3_Programming.png',
    issueDate: '2023-09-15',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/DL6IDFS65YVP',
    skills: ['Python', 'Programming', 'Data Structures', 'Object-Oriented Programming', 'File Handling'],
    order: 1,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '2',
    title: 'Generative AI for Software Developers',
    issuer: 'Coursera & IBM',
    description: 'This specialization provides a comprehensive introduction to generative AI for software developers. It covers the fundamentals of generative models, prompt engineering, and how to integrate generative AI into software applications. The program includes practical projects to apply these concepts in real-world scenarios.',
    image: '/images/certificates/Generative_AI_for_Software_Developers.png',
    issueDate: '2023-11-20',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/CONL6GU9WBG4',
    skills: ['Generative AI', 'Prompt Engineering', 'Software Development', 'AI Integration', 'Machine Learning'],
    order: 2,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '3',
    title: 'Foundations of Cybersecurity',
    issuer: 'Coursera & Google',
    description: 'This course introduces the core concepts of cybersecurity and provides a foundation for understanding security principles, threats, and defense mechanisms. It covers security frameworks, risk management, and basic security controls that organizations implement to protect their digital assets.',
    image: '/images/certificates/Foundations_of_Cybersecurity.png',
    issueDate: '2023-08-05',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/4RPCZ4P05PKB',
    skills: ['Cybersecurity', 'Security Frameworks', 'Risk Management', 'Network Security', 'Security Controls'],
    order: 3,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '4',
    title: 'Introduction to HTML, CSS, & JavaScript',
    issuer: 'Coursera & IBM',
    description: 'This course provides a comprehensive introduction to the three core technologies of web development: HTML for structure, CSS for styling, and JavaScript for interactivity. It covers the fundamentals of creating and styling web pages and adding dynamic functionality through JavaScript.',
    image: '/images/certificates/Introduction_to_HTML_CSS_&_JavaScript.png',
    issueDate: '2023-07-10',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/NQN98HM46LB0',
    skills: ['HTML', 'CSS', 'JavaScript', 'Web Development', 'Front-end Development'],
    order: 4,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '5',
    title: 'Object-Oriented Design',
    issuer: 'Coursera & University of Alberta',
    description: 'This course explores the principles and concepts of object-oriented design and programming. It covers class design, inheritance, polymorphism, and design patterns. The course teaches how to apply these concepts to create flexible, maintainable, and reusable software systems.',
    image: '/images/certificates/Object-Oriented_Design.png',
    issueDate: '2023-06-25',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/K1N2D79JAUV8',
    skills: ['Object-Oriented Programming', 'Software Design', 'Design Patterns', 'UML', 'Software Architecture'],
    order: 5,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '6',
    title: 'Supervised Machine Learning: Regression and Classification',
    issuer: 'Coursera & Stanford University',
    description: 'This course provides a comprehensive introduction to supervised machine learning, focusing on regression and classification algorithms. It covers linear regression, logistic regression, gradient descent, and the fundamentals of model training and evaluation.',
    image: '/images/certificates/Supervised_Machine_Learning.png',
    issueDate: '2023-05-15',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/R48M58N8ANIF',
    skills: ['Machine Learning', 'Regression', 'Classification', 'Python', 'Model Evaluation'],
    order: 6,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '7',
    title: 'Programming with JavaScript',
    issuer: 'Coursera & Meta',
    description: 'This course teaches the fundamentals of programming with JavaScript. It covers core concepts like variables, data types, functions, loops, and DOM manipulation. The course includes practical exercises to build interactive web applications using JavaScript.',
    image: '/images/certificates/Programming_with_JavaScript.png',
    issueDate: '2023-04-20',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/IUJC6K6I5RWP',
    skills: ['JavaScript', 'Web Development', 'DOM Manipulation', 'Front-end Development', 'Programming Logic'],
    order: 7,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '8',
    title: 'Introduction to Java',
    issuer: 'Coursera & Duke University',
    description: 'This course introduces the fundamentals of Java programming. It covers basic syntax, object-oriented concepts, data structures, and file I/O in Java. The course includes hands-on programming assignments to build practical Java development skills.',
    image: '/images/certificates/Introduction_to_Java.png',
    issueDate: '2023-03-10',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/MUSB84MUEDSQ',
    skills: ['Java', 'Object-Oriented Programming', 'Data Structures', 'Software Development', 'Programming'],
    order: 8,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '9',
    title: 'Inheritance and Data Structures in Java',
    issuer: 'Coursera & Duke University',
    description: 'This course builds on basic Java knowledge to explore advanced concepts like inheritance, interfaces, and data structures. It covers how to implement and use common data structures in Java and how to leverage inheritance for code reuse and extensibility.',
    image: '/images/certificates/Inheritance_and_Data_Structures_in_Java.png',
    issueDate: '2023-04-05',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/UKBCUY4VGUWH',
    skills: ['Java', 'Inheritance', 'Data Structures', 'Object-Oriented Programming', 'Algorithms'],
    order: 9,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '10',
    title: 'LinkedIn Workshop',
    issuer: 'GrowthSchool',
    description: 'This workshop provides comprehensive strategies for optimizing LinkedIn profiles and leveraging the platform for professional networking and career growth. It covers profile optimization, content creation, engagement strategies, and techniques for building a professional brand on LinkedIn.',
    image: '/images/certificates/Linkedin_Workshop.png',
    issueDate: '2023-10-15',
    credentialUrl: 'https://learners.growthschool.io/certificate/00bac5ff-9844-4120-9e57-fabd081a7027',
    skills: ['LinkedIn', 'Personal Branding', 'Professional Networking', 'Content Strategy', 'Career Development'],
    order: 10,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '11',
    title: '2 Day AI Mastery Workshop',
    issuer: 'Outskill',
    description: 'This intensive two-day workshop covers the fundamentals and practical applications of artificial intelligence. Participants learn about machine learning algorithms, neural networks, and how to implement AI solutions for real-world problems. The workshop includes hands-on exercises and project-based learning.',
    image: '/images/certificates/2_Day_AI_Mastery_Workshop.png',
    issueDate: '2023-11-30',
    credentialUrl: '',
    skills: ['Artificial Intelligence', 'Machine Learning', 'Neural Networks', 'AI Applications', 'Problem Solving'],
    order: 11,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '12',
    title: 'Ingenious Hackathon 6.0',
    issuer: 'Ahmedabad University',
    description: 'This certificate recognizes participation and achievement in the Ingenious Hackathon 6.0, a competitive event where participants develop innovative solutions to real-world problems within a limited timeframe. The hackathon focuses on creativity, technical skills, and teamwork in developing functional prototypes.',
    image: '/images/certificates/AU_Hackathon.png',
    issueDate: '2023-12-10',
    credentialUrl: '',
    skills: ['Hackathon', 'Problem Solving', 'Software Development', 'Teamwork', 'Innovation'],
    order: 12,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '13',
    title: 'GitHub Foundations',
    issuer: 'GitHub',
    description: 'This certification validates proficiency in GitHub fundamentals, including repository management, version control, collaboration workflows, and best practices for using GitHub effectively. It demonstrates the ability to use GitHub for project management and code collaboration.',
    image: '/images/certificates/GitHub_Foundations.png',
    issueDate: '2024-01-15',
    credentialUrl: 'https://www.credly.com/badges/279d09f0-6b04-417e-82df-310670f7043a/print',
    skills: ['GitHub', 'Version Control', 'Git', 'Repository Management', 'Collaboration', 'Project Management'],
    order: 13,
    createdAt: new Date().toISOString(),
  },
];

// Mock contact form submission
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const submitMockContactForm = async (_data: ContactFormData): Promise<{ success: boolean; message: string }> => {
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 1000));

  // Always return success for mock data
  return {
    success: true,
    message: 'Thank you for your message! This is a mock response as the site is currently deployed on GitHub Pages without a backend server.',
  };
};
