import { Project, Skill, ContactFormData, SkillCategory, Book, Certification } from '@/types';
import { getAssetPath } from './utils';

// Mock Projects
export const projects: Project[] = [
  {
    _id: '4',
    title: 'Pharmacy Management System',
    description: 'A console-based system using Java and PostgreSQL for managing drug inventory and transactions. This application helps pharmacies track inventory, manage prescriptions, and process sales.\n\nThe system includes features for user authentication, inventory management, sales tracking, and reporting.',
    image: getAssetPath('/images/projects/pharmacy-system.jpg'),
    technologies: ['Java', 'PostgreSQL', 'JDBC', 'Console App'],
    githubUrl: 'https://github.com/AnkushGitRepo/Pharmacy-Management-System',
    liveUrl: '',
    featured: true,
    category: 'Desktop Application',
    createdAt: new Date().toISOString(),
  },
];

// Mock Skills
export const skills: Skill[] = [
  // Languages
  {
    _id: '1',
    name: 'Java',
    category: SkillCategory.LANGUAGES,
    icon: '/images/skills/icons8-java.svg',
  },
  {
    _id: '2',
    name: 'Python',
    category: SkillCategory.LANGUAGES,
    icon: '/images/skills/icons8-python.svg',
  },
  {
    _id: '3',
    name: 'JavaScript',
    category: SkillCategory.LANGUAGES,
    icon: '/images/skills/icons8-javascript.svg',
  },
  {
    _id: '4',
    name: 'HTML',
    category: SkillCategory.LANGUAGES,
    icon: '/images/skills/icons8-html5.svg',
  },
  {
    _id: '5',
    name: 'CSS',
    category: SkillCategory.LANGUAGES,
    icon: '/images/skills/icons8-css.svg',
  },
  {
    _id: '6',
    name: 'TypeScript',
    category: SkillCategory.LANGUAGES,
    icon: '/images/skills/icons8-typescript.svg',
  },

  // Frameworks & Libraries
  {
    _id: '7',
    name: 'React',
    category: SkillCategory.FRAMEWORKS,
    icon: '/images/skills/icons8-react.svg',
  },
  {
    _id: '8',
    name: 'Node.js',
    category: SkillCategory.FRAMEWORKS,
    icon: '/images/skills/icons8-nodejs.svg',
  },
  {
    _id: '9',
    name: 'Express.js',
    category: SkillCategory.FRAMEWORKS,
    icon: '/images/skills/icons8-express-js.svg',
  },
  {
    _id: '10',
    name: 'Bootstrap',
    category: SkillCategory.FRAMEWORKS,
    icon: '/images/skills/icons8-bootstrap.svg',
  },
  {
    _id: '11',
    name: 'Tailwind CSS',
    category: SkillCategory.FRAMEWORKS,
    icon: '/images/skills/icons8-tailwind-css.svg',
  },

  // Databases
  {
    _id: '12',
    name: 'MySQL',
    category: SkillCategory.DATABASES,
    icon: '/images/skills/icons8-mysql.svg',
  },
  {
    _id: '13',
    name: 'PostgreSQL',
    category: SkillCategory.DATABASES,
    icon: '/images/skills/icons8-postgres.svg',
  },
  {
    _id: '14',
    name: 'MongoDB',
    category: SkillCategory.DATABASES,
    icon: '/images/skills/MongoDB.svg',
  },
  {
    _id: '15',
    name: 'Redis',
    category: SkillCategory.DATABASES,
    icon: '/images/skills/icons8-redis.svg',
  },

  // Tools & IDEs
  {
    _id: '16',
    name: 'Git',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-git.svg',
  },
  {
    _id: '17',
    name: 'GitHub',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-github.svg',
  },
  {
    _id: '18',
    name: 'VS Code',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-visual-studio.svg',
  },
  {
    _id: '19',
    name: 'IntelliJ IDEA',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-intellij-idea.svg',
  },
  {
    _id: '20',
    name: 'PyCharm',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-pycharm.svg',
  },
  {
    _id: '21',
    name: 'WebStorm',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-webstorm.svg',
  },
  {
    _id: '22',
    name: 'Jupyter',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-jupyter.svg',
  },
  {
    _id: '23',
    name: 'Figma',
    category: SkillCategory.TOOLS,
    icon: '/images/skills/icons8-figma.svg',
  },
];

// Mock Books
export const books: Book[] = [
  {
    _id: '1',
    title: 'Rich Dad Poor Dad',
    author: 'Robert T. Kiyosaki',
    image: getAssetPath('/images/Books/Rich_Dad_Poor_Dad.png'),
    coverImage: getAssetPath('/images/Books/Rich_Dad_Poor_Dad.png'),
    description: 'What the Rich Teach Their Kids About Money That the Poor and Middle Class Do Not!',
    review: 'This book completely changed my perspective on money and investing. Kiyosaki explains complex financial concepts through simple storytelling, making it accessible to everyone. The distinction between assets and liabilities has been a guiding principle in my financial decisions.',
    genre: ['Personal Finance', 'Business', 'Self-Help'],
    goodreadsLink: 'https://www.goodreads.com/book/show/69571.Rich_Dad_Poor_Dad',
    order: 1,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '2',
    title: 'Elon Musk',
    author: 'Ashlee Vance',
    image: getAssetPath('/images/Books/Elon_Musk_By_Ashlee_Vance.webp'),
    coverImage: getAssetPath('/images/Books/Elon_Musk_By_Ashlee_Vance.webp'),
    description: 'Tesla, SpaceX, and the Quest for a Fantastic Future',
    review: 'An inspiring biography that details Musk\'s relentless drive and vision. The book provides fascinating insights into how Musk built multiple revolutionary companies and overcame seemingly impossible challenges. His work ethic and ability to think at scale is truly remarkable.',
    genre: ['Biography', 'Business', 'Technology'],
    goodreadsLink: 'https://www.goodreads.com/book/show/25541028-elon-musk',
    order: 2,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '3',
    title: 'Zero to One',
    author: 'Peter Thiel',
    image: getAssetPath('/images/Books/zero_to_one_peter_thiel_.png'),
    coverImage: getAssetPath('/images/Books/zero_to_one_peter_thiel_.png'),
    description: 'Notes on Startups, or How to Build the Future',
    review: 'Thiel presents a contrarian view on innovation and entrepreneurship that challenges conventional thinking. His emphasis on creating something truly new (going from 0 to 1) rather than iterating on existing ideas has influenced how I approach problem-solving and innovation.',
    genre: ['Business', 'Entrepreneurship', 'Technology'],
    goodreadsLink: 'https://www.goodreads.com/book/show/18050143-zero-to-one',
    order: 3,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '4',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    image: getAssetPath('/images/Books/The_Psychology_of_Money.jpg'),
    coverImage: getAssetPath('/images/Books/The_Psychology_of_Money.jpg'),
    description: 'Timeless lessons on wealth, greed, and happiness',
    review: 'Housel presents financial concepts through compelling stories that highlight how psychology affects our financial decisions. The book changed how I think about money, success, and happiness. The concept that financial decisions are not just about math but about behavior and personal history was eye-opening.',
    genre: ['Finance', 'Psychology', 'Economics'],
    goodreadsLink: 'https://www.goodreads.com/book/show/41881472-the-psychology-of-money',
    order: 4,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '5',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    image: getAssetPath('/images/Books/Thinking_Fast_and_Slow.webp'),
    coverImage: getAssetPath('/images/Books/Thinking_Fast_and_Slow.webp'),
    description: 'A groundbreaking tour of the mind explaining the two systems that drive the way we think',
    review: 'Kahneman\'s exploration of cognitive biases and the two systems of thinking provides profound insights into human decision-making. This book has made me more aware of my own thinking patterns and biases, helping me make more rational decisions in both personal and professional contexts.',
    genre: ['Psychology', 'Economics', 'Science'],
    goodreadsLink: 'https://www.goodreads.com/book/show/11468377-thinking-fast-and-slow',
    order: 5,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '6',
    title: 'Do Epic Shit',
    author: 'Ankur Warikoo',
    image: getAssetPath('/images/Books/Do_Epic_Shit.png'),
    coverImage: getAssetPath('/images/Books/Do_Epic_Shit.png'),
    description: 'A collection of lessons on life, career, failure, and success',
    review: 'Warikoo offers practical advice on personal growth, career development, and entrepreneurship in a straightforward, no-nonsense manner. The book\'s bite-sized chapters make complex life lessons accessible and actionable. I particularly appreciated his insights on embracing failure as a learning opportunity.',
    genre: ['Self-Help', 'Career', 'Motivation'],
    goodreadsLink: 'https://www.goodreads.com/book/show/59795331-do-epic-shit',
    order: 6,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '7',
    title: 'Hooked',
    author: 'Nir Eyal',
    image: getAssetPath('/images/Books/Hooked-Book.png'),
    coverImage: getAssetPath('/images/Books/Hooked-Book.png'),
    description: 'How to Build Habit-Forming Products',
    review: 'Eyal presents a practical framework for creating products that naturally integrate into users\' lives. The Hook Model (trigger, action, variable reward, investment) has been invaluable in my approach to product design and user experience. This book is essential reading for anyone interested in building engaging digital products.',
    genre: ['Business', 'Psychology', 'Design'],
    goodreadsLink: 'https://www.goodreads.com/book/show/22668729-hooked',
    order: 7,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '8',
    title: 'One Up On Wall Street',
    author: 'Peter Lynch',
    image: getAssetPath('/images/Books/One_Up_On_Wall_Street.webp'),
    coverImage: getAssetPath('/images/Books/One_Up_On_Wall_Street.webp'),
    description: 'How To Use What You Already Know To Make Money In The Market',
    review: 'Lynch demystifies investing and argues that individual investors can outperform professionals by leveraging their personal knowledge and experiences. His practical approach to identifying investment opportunities in everyday life has changed how I evaluate potential investments. The concept of "invest in what you know" has been particularly valuable.',
    genre: ['Finance', 'Investing', 'Business'],
    goodreadsLink: 'https://www.goodreads.com/book/show/762462.One_Up_On_Wall_Street',
    order: 8,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '9',
    title: 'Bhagavad Gita As It Is',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    image: getAssetPath('/images/Books/Bhagavad_Gita_As_It_Is-Englsiih.png'),
    coverImage: getAssetPath('/images/Books/Bhagavad_Gita_As_It_Is-Englsiih.png'),
    description: 'The definitive guide to understanding the essence of Bhagavad Gita',
    review: 'This translation and commentary provides profound insights into the timeless wisdom of the Bhagavad Gita. The teachings on duty, purpose, and spiritual growth have been transformative in my approach to life\'s challenges. The concept of performing one\'s duties without attachment to results has been particularly impactful in my personal and professional life.',
    genre: ['Philosophy', 'Spirituality', 'Religion'],
    goodreadsLink: 'https://www.goodreads.com/book/show/24006137-the-bhagavad-gita-as-it-is',
    order: 9,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '10',
    title: 'Attitude Is Everything',
    author: 'Jeff Keller',
    image: getAssetPath('/images/Books/Attitude_Is_Everthing.webp'),
    coverImage: getAssetPath('/images/Books/Attitude_Is_Everthing.webp'),
    description: 'Change Your Attitude... Change Your Life!',
    review: 'Keller presents a compelling case for how our attitudes shape our experiences and outcomes. The practical strategies for maintaining a positive mindset have been valuable in navigating challenges and setbacks. This book reinforced my belief that perspective is often more important than circumstances in determining success and happiness.',
    genre: ['Self-Help', 'Psychology', 'Motivation'],
    goodreadsLink: 'https://www.goodreads.com/book/show/482579.Attitude_Is_Everything',
    order: 10,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '11',
    title: 'The 48 Laws of Power',
    author: 'Robert Greene',
    image: getAssetPath('/images/Books/48_Laws_of_Power.webp'),
    coverImage: getAssetPath('/images/Books/48_Laws_of_Power.webp'),
    description: 'A amoral, cunning, ruthless, and instructive manual on gaining and maintaining power',
    review: 'Greene\'s analysis of historical power dynamics provides fascinating insights into human behavior and social influence. While some laws may seem Machiavellian, understanding these principles has helped me navigate complex social and professional situations more effectively. The historical examples make abstract concepts concrete and memorable.',
    genre: ['Psychology', 'History', 'Self-Help'],
    goodreadsLink: 'https://www.goodreads.com/book/show/1303.The_48_Laws_of_Power',
    order: 11,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '12',
    title: 'Influence: The Psychology of Persuasion',
    author: 'Robert B. Cialdini',
    image: getAssetPath('/images/Books/Influence_The_Psychology_Of_Persuasion.jpg'),
    coverImage: getAssetPath('/images/Books/Influence_The_Psychology_Of_Persuasion.jpg'),
    description: 'The classic book on the psychology of persuasion',
    review: 'Cialdini\'s exploration of the six principles of influence (reciprocity, commitment, social proof, authority, liking, and scarcity) has been invaluable in understanding how and why people say "yes." This knowledge has improved my communication skills and helped me recognize when these principles are being used on me. The real-world examples make the concepts easy to understand and apply.',
    genre: ['Psychology', 'Business', 'Marketing'],
    goodreadsLink: 'https://www.goodreads.com/book/show/28815.Influence',
    order: 12,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '13',
    title: 'The Compound Effect',
    author: 'Darren Hardy',
    image: getAssetPath('/images/Books/The_Compound_Effect.jpg'),
    coverImage: getAssetPath('/images/Books/The_Compound_Effect.jpg'),
    description: 'Jumpstart your income, your life, your success',
    review: 'Hardy\'s exploration of how small, consistent actions compound over time has been transformative in my approach to personal and professional growth. The practical strategies for creating positive habits and eliminating negative ones have helped me make meaningful progress toward my goals. The concept that success is built through daily disciplines rather than dramatic changes resonates deeply.',
    genre: ['Self-Help', 'Personal Development', 'Business'],
    goodreadsLink: 'https://www.goodreads.com/book/show/9420697-the-compound-effect',
    order: 13,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '14',
    title: 'How to Talk to Anyone',
    author: 'Leil Lowndes',
    image: getAssetPath('/images/Books/How_t0_Talk_To_Anyone.webp'),
    coverImage: getAssetPath('/images/Books/How_t0_Talk_To_Anyone.webp'),
    description: '92 Little Tricks for Big Success in Relationships',
    review: 'Lowndes provides practical, actionable communication techniques that have improved my social and professional interactions. The book\'s approach to building rapport, active listening, and nonverbal communication has been particularly valuable. I\'ve found that implementing even a few of these techniques has significantly enhanced my ability to connect with others.',
    genre: ['Communication', 'Self-Help', 'Psychology'],
    goodreadsLink: 'https://www.goodreads.com/book/show/35210.How_to_Talk_to_Anyone',
    order: 14,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '15',
    title: 'Read People Like a Book',
    author: 'Patrick King',
    image: getAssetPath('/images/Books/Read_People_Like_A_Book.jpg'),
    coverImage: getAssetPath('/images/Books/Read_People_Like_A_Book.jpg'),
    description: 'How to Analyze, Understand, and Predict People\'s Emotions, Thoughts, Intentions, and Behaviors',
    review: 'King offers practical insights into understanding human behavior through nonverbal cues, speech patterns, and contextual analysis. The techniques for reading micro-expressions and body language have been particularly useful in improving my emotional intelligence and interpersonal awareness. This book has helped me become more attuned to the subtleties of human communication.',
    genre: ['Psychology', 'Communication', 'Self-Help'],
    goodreadsLink: 'https://www.goodreads.com/book/show/56199402-read-people-like-a-book',
    order: 15,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '16',
    title: 'Blue Ocean Strategy',
    author: 'W. Chan Kim & Renée Mauborgne',
    image: getAssetPath('/images/Books/Bluw_Ocean_Strategy.png'),
    coverImage: getAssetPath('/images/Books/Bluw_Ocean_Strategy.png'),
    description: 'How to Create Uncontested Market Space and Make the Competition Irrelevant',
    review: 'Kim and Mauborgne present a compelling framework for creating new market spaces rather than competing in existing ones. The concept of value innovation—simultaneously pursuing differentiation and low cost—has influenced my approach to business strategy and product development. The case studies provide practical examples of how companies have successfully implemented blue ocean strategies.',
    genre: ['Business', 'Strategy', 'Marketing'],
    goodreadsLink: 'https://www.goodreads.com/book/show/4898.Blue_Ocean_Strategy',
    order: 16,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '17',
    title: 'One Thousand Ways to Make $1000',
    author: 'F.C. Minaker',
    image: getAssetPath('/images/Books/One_Thousand_Ways_to_Make_$1000.png'),
    coverImage: getAssetPath('/images/Books/One_Thousand_Ways_to_Make_$1000.png'),
    description: 'Practical suggestions, plans and ideas for the man who needs more money',
    review: 'Despite being written decades ago, this book offers timeless principles of entrepreneurship and wealth creation. The diverse business ideas and practical approach to starting small have been inspiring. What I found most valuable was the emphasis on resourcefulness, creativity, and taking action—principles that remain relevant in today\'s economy.',
    genre: ['Business', 'Entrepreneurship', 'Finance'],
    goodreadsLink: 'https://www.goodreads.com/book/show/27424325-one-thousand-ways-to-make-1000',
    order: 17,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '18',
    title: 'The Warren Buffett Way',
    author: 'Robert G. Hagstrom',
    image: getAssetPath('/images/Books/Warren_Buffett_Way.webp'),
    coverImage: getAssetPath('/images/Books/Warren_Buffett_Way.webp'),
    description: 'Investment Strategies of the World\'s Greatest Investor',
    review: 'Hagstrom provides a comprehensive analysis of Buffett\'s investment philosophy and methodology. The principles of focusing on business fundamentals, having a margin of safety, and investing for the long term have significantly influenced my approach to investing. The case studies of Buffett\'s major investments offer practical examples of these principles in action.',
    genre: ['Finance', 'Investing', 'Business'],
    goodreadsLink: 'https://goodreads.com/book/show/209956.The_Warren_Buffett_Way',
    order: 18,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '19',
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    image: getAssetPath('/images/Books/Think_and_Grow_Rich_by_Napoleon_hill.jpg'),
    coverImage: getAssetPath('/images/Books/Think_and_Grow_Rich_by_Napoleon_hill.jpg'),
    description: 'Think and Grow Rich is a guide to success by Napoleon Hill, which was first published in 1937 following the Great Depression. It was immediately welcomed as an antidote to hard times and remained a bestseller for decades.',
    review: 'This timeless classic offers powerful insights into the psychology of success. Hill\'s principles of desire, faith, and persistence have been instrumental in shaping my mindset toward achievement. The concept of the "Master Mind" alliance particularly resonated with me, showing the importance of surrounding yourself with the right people.',
    genre: ['Self-Help', 'Business', 'Personal Development', 'Finance'],
    goodreadsLink: 'https://www.goodreads.com/book/show/30186948-think-and-grow-rich',
    order: 19,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '20',
    title: 'How to Win Friends and Influence People',
    author: 'Dale Carnegie',
    image: getAssetPath('/images/Books/how_to_win_friends_and_influence_people.jpg'),
    coverImage: getAssetPath('/images/Books/how_to_win_friends_and_influence_people.jpg'),
    description: 'Since its release in 1936, How to Win Friends and Influence People has sold more than 30 million copies. Dale Carnegie\'s first book is a timeless bestseller, packed with rock-solid advice that has carried thousands of now famous people up the ladder of success in their business and personal lives.',
    review: 'Carnegie\'s principles on human relations have been invaluable in both my personal and professional life. The simple yet profound advice on how to genuinely connect with others, handle disagreements, and influence people positively has transformed my approach to communication and leadership.',
    genre: ['Self-Help', 'Psychology', 'Business', 'Communication'],
    goodreadsLink: 'https://www.goodreads.com/book/show/4865.How_to_Win_Friends_Influence_People',
    order: 20,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '21',
    title: 'The 5 AM Club',
    author: 'Robin Sharma',
    image: getAssetPath('/images/Books/The_5_AM_Club.jpg'),
    coverImage: getAssetPath('/images/Books/The_5_AM_Club.jpg'),
    description: 'The 5 AM Club presents a revolutionary morning routine that helps you maximize productivity, improve health, and achieve success. Through the 20/20/20 formula, the book teaches how to use the first hour of your day to move (exercise), reflect (meditate/journal), and grow (learn). It emphasizes that world-class performance comes from owning your morning and establishing powerful daily habits.',
    review: 'This book completely transformed my approach to mornings and productivity. Sharma\'s 20/20/20 formula provided me with a practical framework that boosted my energy, clarity, and focus throughout the day. The concept of using the "Victory Hour" to invest in my physical, mental, and spiritual growth has been game-changing. While the habit was difficult to establish initially, the benefits to my overall wellbeing and productivity have been absolutely worth the effort.',
    genre: ['Self-Help', 'Personal Development', 'Productivity', 'Habits'],
    goodreadsLink: 'https://www.goodreads.com/book/show/37502596-the-5-am-club',
    order: 21,
    createdAt: new Date().toISOString(),
  },
];

// Mock Certifications
export const certifications: Certification[] = [
  {
    _id: '1',
    title: 'Python 3 Programming',
    issuer: 'Coursera & University of Michigan',
    description: 'This specialization teaches the fundamentals of Python 3 programming. It covers Python basics, data structures, file handling, and advanced concepts like object-oriented programming. The specialization includes hands-on projects to build practical programming skills.',
    image: '/images/certificates/Python_3_Programming.png',
    issueDate: '2023-09-15',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/DL6IDFS65YVP',
    skills: ['Python', 'Programming', 'Data Structures', 'Object-Oriented Programming', 'File Handling'],
    order: 1,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '2',
    title: 'Generative AI for Software Developers',
    issuer: 'Coursera & IBM',
    description: 'This specialization provides a comprehensive introduction to generative AI for software developers. It covers the fundamentals of generative models, prompt engineering, and how to integrate generative AI into software applications. The program includes practical projects to apply these concepts in real-world scenarios.',
    image: '/images/certificates/Generative_AI_for_Software_Developers.png',
    issueDate: '2023-11-20',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/specialization/CONL6GU9WBG4',
    skills: ['Generative AI', 'Prompt Engineering', 'Software Development', 'AI Integration', 'Machine Learning'],
    order: 2,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '3',
    title: 'Foundations of Cybersecurity',
    issuer: 'Coursera & Google',
    description: 'This course introduces the core concepts of cybersecurity and provides a foundation for understanding security principles, threats, and defense mechanisms. It covers security frameworks, risk management, and basic security controls that organizations implement to protect their digital assets.',
    image: '/images/certificates/Foundations_of_Cybersecurity.png',
    issueDate: '2023-08-05',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/4RPCZ4P05PKB',
    skills: ['Cybersecurity', 'Security Frameworks', 'Risk Management', 'Network Security', 'Security Controls'],
    order: 3,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '4',
    title: 'Introduction to HTML, CSS, & JavaScript',
    issuer: 'Coursera & IBM',
    description: 'This course provides a comprehensive introduction to the three core technologies of web development: HTML for structure, CSS for styling, and JavaScript for interactivity. It covers the fundamentals of creating and styling web pages and adding dynamic functionality through JavaScript.',
    image: '/images/certificates/Introduction_to_HTML_CSS_&_JavaScript.png',
    issueDate: '2023-07-10',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/NQN98HM46LB0',
    skills: ['HTML', 'CSS', 'JavaScript', 'Web Development', 'Front-end Development'],
    order: 4,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '5',
    title: 'Object-Oriented Design',
    issuer: 'Coursera & University of Alberta',
    description: 'This course explores the principles and concepts of object-oriented design and programming. It covers class design, inheritance, polymorphism, and design patterns. The course teaches how to apply these concepts to create flexible, maintainable, and reusable software systems.',
    image: '/images/certificates/Object-Oriented_Design.png',
    issueDate: '2023-06-25',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/K1N2D79JAUV8',
    skills: ['Object-Oriented Programming', 'Software Design', 'Design Patterns', 'UML', 'Software Architecture'],
    order: 5,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '6',
    title: 'Supervised Machine Learning: Regression and Classification',
    issuer: 'Coursera & Stanford University',
    description: 'This course provides a comprehensive introduction to supervised machine learning, focusing on regression and classification algorithms. It covers linear regression, logistic regression, gradient descent, and the fundamentals of model training and evaluation.',
    image: '/images/certificates/Supervised_Machine_Learning.png',
    issueDate: '2023-05-15',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/R48M58N8ANIF',
    skills: ['Machine Learning', 'Regression', 'Classification', 'Python', 'Model Evaluation'],
    order: 6,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '7',
    title: 'Programming with JavaScript',
    issuer: 'Coursera & Meta',
    description: 'This course teaches the fundamentals of programming with JavaScript. It covers core concepts like variables, data types, functions, loops, and DOM manipulation. The course includes practical exercises to build interactive web applications using JavaScript.',
    image: '/images/certificates/Programming_with_JavaScript.png',
    issueDate: '2023-04-20',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/IUJC6K6I5RWP',
    skills: ['JavaScript', 'Web Development', 'DOM Manipulation', 'Front-end Development', 'Programming Logic'],
    order: 7,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '8',
    title: 'Introduction to Java',
    issuer: 'Coursera & Duke University',
    description: 'This course introduces the fundamentals of Java programming. It covers basic syntax, object-oriented concepts, data structures, and file I/O in Java. The course includes hands-on programming assignments to build practical Java development skills.',
    image: '/images/certificates/Introduction_to_Java.png',
    issueDate: '2023-03-10',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/MUSB84MUEDSQ',
    skills: ['Java', 'Object-Oriented Programming', 'Data Structures', 'Software Development', 'Programming'],
    order: 8,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '9',
    title: 'Inheritance and Data Structures in Java',
    issuer: 'Coursera & Duke University',
    description: 'This course builds on basic Java knowledge to explore advanced concepts like inheritance, interfaces, and data structures. It covers how to implement and use common data structures in Java and how to leverage inheritance for code reuse and extensibility.',
    image: '/images/certificates/Inheritance_and_Data_Structures_in_Java.png',
    issueDate: '2023-04-05',
    credentialUrl: 'https://www.coursera.org/account/accomplishments/verify/UKBCUY4VGUWH',
    skills: ['Java', 'Inheritance', 'Data Structures', 'Object-Oriented Programming', 'Algorithms'],
    order: 9,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '10',
    title: 'LinkedIn Workshop',
    issuer: 'GrowthSchool',
    description: 'This workshop provides comprehensive strategies for optimizing LinkedIn profiles and leveraging the platform for professional networking and career growth. It covers profile optimization, content creation, engagement strategies, and techniques for building a professional brand on LinkedIn.',
    image: '/images/certificates/Linkedin_Workshop.png',
    issueDate: '2023-10-15',
    credentialUrl: 'https://learners.growthschool.io/certificate/00bac5ff-9844-4120-9e57-fabd081a7027',
    skills: ['LinkedIn', 'Personal Branding', 'Professional Networking', 'Content Strategy', 'Career Development'],
    order: 10,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '11',
    title: '2 Day AI Mastery Workshop',
    issuer: 'Outskill',
    description: 'This intensive two-day workshop covers the fundamentals and practical applications of artificial intelligence. Participants learn about machine learning algorithms, neural networks, and how to implement AI solutions for real-world problems. The workshop includes hands-on exercises and project-based learning.',
    image: '/images/certificates/2_Day_AI_Mastery_Workshop.png',
    issueDate: '2023-11-30',
    credentialUrl: '',
    skills: ['Artificial Intelligence', 'Machine Learning', 'Neural Networks', 'AI Applications', 'Problem Solving'],
    order: 11,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '12',
    title: 'Ingenious Hackathon 6.0',
    issuer: 'Ahmedabad University',
    description: 'This certificate recognizes participation and achievement in the Ingenious Hackathon 6.0, a competitive event where participants develop innovative solutions to real-world problems within a limited timeframe. The hackathon focuses on creativity, technical skills, and teamwork in developing functional prototypes.',
    image: '/images/certificates/AU_Hackathon.png',
    issueDate: '2023-12-10',
    credentialUrl: '',
    skills: ['Hackathon', 'Problem Solving', 'Software Development', 'Teamwork', 'Innovation'],
    order: 12,
    createdAt: new Date().toISOString(),
  },
  {
    _id: '13',
    title: 'GitHub Foundations',
    issuer: 'GitHub',
    description: 'This certification validates proficiency in GitHub fundamentals, including repository management, version control, collaboration workflows, and best practices for using GitHub effectively. It demonstrates the ability to use GitHub for project management and code collaboration.',
    image: '/images/certificates/GitHub_Foundations.png',
    issueDate: '2024-01-15',
    credentialUrl: 'https://www.credly.com/badges/279d09f0-6b04-417e-82df-310670f7043a/print',
    skills: ['GitHub', 'Version Control', 'Git', 'Repository Management', 'Collaboration', 'Project Management'],
    order: 13,
    createdAt: new Date().toISOString(),
  },
];

// Mock contact form submission
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const submitMockContactForm = async (_data: ContactFormData): Promise<{ success: boolean; message: string }> => {
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 1000));

  // Always return success for mock data
  return {
    success: true,
    message: 'Thank you for your message! This is a mock response as the site is currently deployed on GitHub Pages without a backend server.',
  };
};
